# Jupyter Book configuration

title: HMMPY
author: Mike Hamilton
copyright: 2026

exclude_patterns: [".DS_Store", "Thumbs.db"]

html:
  title: HMMPY Documentation

execute:
  execute_notebooks: cache

parse:
  myst_enable_extensions:
    - colon_fence
    - linkify
    - substitution
    - tasklist
